service: basic-app

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: ./

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**/*
