---
exclude_paths:
  - "CHANGELOG.md"
  - "**/CHANGELOG.md"
  - "packages/deprecated/**"
  - "packages/libs/core/sharp_node_modules/**"
  - "packages/serverless-components/nextjs-component/examples/**"
