sudo: false
os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - "10.16"
  - "12.7.0"
install:
  - npm ci
  - cd packages/serverless-nextjs-plugin && npm ci && cd ../../
  - cd packages/serverless-nextjs-component && npm ci && cd ../../
  - cd integration/app-with-serverless-offline && npm ci && cd ../../
script:
  - npm run lint
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run coveralls; fi
  - npm run integration
