sudo: false
os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - "10.16"
  - "12.7.0"
install:
  - npm install
  - cd packages/serverless-nextjs-plugin && npm install && cd ../../
  - cd packages/serverless-nextjs-component && npm install && cd ../../
  - cd integration/app-with-serverless-offline && npm install && cd ../../
script:
  - npm run lint
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run coveralls; fi
  - npm run integration
cache:
  directories:
    - "node_modules"
