sudo: false
language: node_js
node_js:
  - "8"
  - "11.10"
install:
  - npm install
  - npm install --prefix integration/app-with-serverless-offline
script:
  - npm run lint
  - npm test
  - npm run coveralls
  - npm run integration
cache:
  directories:
    - "node_modules"
