service: basic-app

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  localPath: "../../packages/serverless-nextjs-plugin"
  modules:
    - index

custom:
  serverless-nextjs:
    pageConfig:
      post:
        memorySize: 2048
    routes:
      - src: post
        path: posts/{id}
        request:
          parameters:
            paths:
              id: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
