next-app:
  component: "../../serverless-components/nextjs-component"
  inputs:
    build:
      postBuildCommands: ["node scripts/post-build-test.js"]
    imageOptimizer: true
    cloudfront:
      defaults:
        forward:
          headers: [Accept] # Needed for image optimizer
