# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

aliases:
  - &environment
    TZ: /usr/share/zoneinfo/America/Los_Angeles

executors:
  linux:
    resource_class: medium+
    docker:
      - image: cimg/node:14.18-browsers
  windows: win/default

orbs:
  aws-cli-linux: circleci/aws-cli@2.0.3
  queue: eddiewebb/queue@1.6.3
  win: circleci/windows@2.3.0
  aws-cli-windows: sensu/awscli-windows@1.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run-e2e-tests:
    parameters:
      os:
        type: string
      app:
        type: string
    executor: << parameters.os >>
    environment: *environment
    steps:
      - checkout

      - when:
          condition:
            equal: [<< parameters.os >>, "linux"]
          steps:
            - aws-cli-linux/install

      - when:
          condition:
            equal: [<< parameters.os >>, "windows"]
          steps:
            - run:
                name: Install AWS CLI v1
                command: pip install awscli --upgrade

      - run:
          name: Print AWS
          command: aws configure list

      - run:
          name: Print Node.js version
          command: node --version

      - restore_cache:
          name: Restore yarn cache
          key: v3-node-{{ arch }}-<< parameters.app >>-{{ checksum "yarn.lock" }}-yarn

      - run:
          name: Setup yarn
          environment:
            NODE_OPTIONS: "--max-old-space-size=6144"
          command: yarn install --immutable --inline-builds

      - run:
          name: Run yarn build
          environment:
            NODE_OPTIONS: "--max-old-space-size=6144"
          command: yarn build

      - run:
          name: Build serverless-patched
          working_directory: ~/project/packages/serverless-patched
          environment:
            NODE_OPTIONS: "--max-old-space-size=6144"
          command: |
            yarn install --immutable
            yarn build

      - when:
          condition:
            not:
              matches:
                pattern: "^prev-.*$"
                value: << parameters.app >>
          steps:
            - run:
                working_directory: ~/project/packages/e2e-tests/<< parameters.app >>
                command: yarn add next@latest

      - run:
          name: Install and run e2e tests
          working_directory: ~/project/packages/e2e-tests/<< parameters.app >>
          environment:
            AWS_DEFAULT_REGION: us-east-1
            WAIT_TIMEOUT: 900
            NODE_OPTIONS: "--max-old-space-size=6144"
            SERVERLESS_CI: true
          command: |
            yarn install --immutable
            yarn e2e:ci
          no_output_timeout: 30m # In case something goes wrong

      - save_cache:
          name: Save yarn cache for future installs
          key: v3-node-{{ arch }}-<< parameters.app >>-{{ checksum "yarn.lock" }}-yarn
          paths:
            - ~/project/.yarn/cache

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  e2e-tests:
    jobs:
      - queue/block_workflow:
          consider-branch: false
          time: "90"
          filters:
            branches:
              ignore: /renovate\/.*/
      - run-e2e-tests:
          filters:
            branches:
              ignore: /renovate\/.*/
          requires:
            - queue/block_workflow
          matrix:
            parameters:
              os:
                - linux
              app:
                # Current minor version of Next.js
                - next-app
                - next-app-experimental
                - next-app-using-serverless-trace
                - next-app-with-trailing-slash
                - next-app-with-base-path
                - next-app-dynamic-routes
                - next-app-with-locales
                - next-app-with-locales-using-serverless-trace
                # Previous minor version of Next.js
                - prev-next-app
                - prev-next-app-with-trailing-slash
                - prev-next-app-with-base-path
                - prev-next-app-dynamic-routes
      - run-e2e-tests:
          filters:
            branches:
              ignore: /renovate\/.*/
          requires:
            - queue/block_workflow
          matrix:
            parameters:
              os:
                - windows
              app:
                - next-app-windows
