prev-next-app:
  component: "../../serverless-components/nextjs-component"
  inputs:
    removeOldLambdaVersions: true
    build:
      postBuildCommands: ["node scripts/post-build-test.js"]
    cloudfront:
      defaults:
        forward:
          headers: [Authorization]
      api/*:
        forward:
          headers: [Authorization]
