service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs8.10

stage: dev
region: eu-west-1

plugins:
  localPath: "../../"
  modules:
    - index

custom:
  serverless-nextjs:
    nextConfigDir: ./

package:
  # exclude everything, except for the page bundles
  exclude:
    - ./**/*
  include:
    # important to use {handler}.* as there will be 2 files per function handler
    - build/serverless/pages/home.*
    - build/serverless/pages/about.*
# TODO: Cleanup after dynamic builds feat is done as functions won't be needed
# functions:
#   home-page:
#     handler: build/serverless/pages/home.render
#     events:
#       - http:
#           path: home
#           method: get
#   about-page:
#     handler: build/serverless/pages/about.render
#     events:
#       - http:
#           path: about
#           method: get
