service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512

stage: dev
region: eu-west-1

plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    nextConfigDir: ./

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**/*
