# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# Finally, it triggers the e2e tests workflow.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master, renovate/**]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --frozen-lockfile

      - run: yarn test

      - run: yarn integration

      - name: Upload code coverage
        if: ${{ matrix.node-version == '12.x' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov

  start-e2e-tests:
    # Note: we only run e2e tests automatically if this PR is not from a fork, as forks won't have access to secrets
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    needs: [build]
    runs-on: [ubuntu-latest]

    steps:
      - name: Mark end-to-end tests as pending
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "Waiting for end-to-end tests to pass"
          state: "pending"
          sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Trigger end-to-end tests workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: End-to-end Tests
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          # FIXME: Passing sha doesn't seem to work, created GitHub ticket here: https://github.community/t/workflow-dispatch-cant-set-ref-to-commit-sha/138132
          # So for now we pass in SHA as an input
          # ref: ${{ github.event.pull_request.head.sha || github.sha }}
          inputs: '{"sha": "${{ github.event.pull_request.head.sha || github.sha }}"}'
