name: End-to-end Tests

on:
  workflow_dispatch:
    pull_request_id:
      description: "Pull Request ID"
      required: false
      default: ""

jobs:
  initialize:
    runs-on: [ubuntu-latest]

    steps:
      - name: Mark end-to-end tests as pending with run URL
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "Waiting for end-to-end tests to pass"
          state: "pending"
          sha: ${{ github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  run-e2e-tests:
    needs: [initialize]
    runs-on: [ubuntu-latest]

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        app:
          - next-app
          - next-app-with-trailing-slash
          - next-app-with-base-path

    steps:
      - uses: actions/checkout@v2

      - name: Checkout pull request
        if: ${{ github.event.inputs.pull_request_id != '' }}
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.inputs.pull_request_id }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --frozen-lockfile
      # TODO: build once and cache for all e2e tests

      - name: Install test utils
        run: |
          cd packages/e2e-tests/test-utils
          yarn --frozen-lockfile

      - name: Wait for existing workflow to complete before e2e tests
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run e2e tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ST }}
          WAIT_TIMEOUT: 600
          APP_NAME: ${{ matrix.app }}
        run: |
          cd packages/e2e-tests/$APP_NAME
          yarn --frozen-lockfile
          yarn e2e:ci

      - name: Mark end-to-end tests as failed
        if: ${{ failure() }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "End-to-end tests have failed"
          state: "failure"
          sha: ${{ github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  finalize:
    needs: run-e2e-tests
    runs-on: [ubuntu-latest]

    steps:
      - name: Mark end-to-end tests as succeeded
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "End-to-end tests have passed"
          state: "success"
          sha: ${{ github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
